---
kubernetes_version: 1.33.7
kubernetes_cluster_name: mycluster

# Enter the group names from your hosts.ini file here:
kubernetes_group_name: k8s_mycluster
kubernetes_masters_group_name: k8s_mycluster_masters
kubernetes_primary_master_group_name: k8s_mycluster_primary_master

kubernetes_max_pods: 123  # default is 110, changed slightly to verify it ends up on nodes

kubernetes_cilium_init_version: 1.33.7  # only the initially installed version, flux takes over afterwards!

# Network settings
kubernetes_api_lb_ip: 1.2.3.4  # externally reachable IP, e.g. from your hosting provider
kubernetes_api_lb_port: 6443

kubernetes_api_cert_sans_extra:
  - "{{ kubernetes_api_lb_ip }}"

kubernetes_network_pod_subnet: 192.168.0.0/17
kubernetes_network_node_cidr_size: 24
kubernetes_network_svc_subnet: 192.168.128.0/20
