---
- name: prepare containerd directory
  file:
    name: /srv/containerd
    state: directory

- name: create bind mount for /var/lib/containerd
  mount:
    src: /srv/containerd
    path: /var/lib/containerd
    fstype: none
    opts: bind,defaults
    state: mounted

- name: make sure the kubernetes_cri_socket variable is configured correctly
  assert:
    msg: "The variable kubernetes_cri_socket is not configured correctly. You might need to move your host to the group kubernetes_cluster or standalone-kubelet!"
    that:
      - kubernetes_cri_socket == "unix:///run/containerd/containerd.sock"

- name: install containerd
  include_role:
    name: mgit_at.roles.containerd

- name: install containerd config for kubernetes
  template:
    src: containerd.toml.j2
    dest: /etc/containerd/config.toml
    mode: 0600
  register: kubernetes_containerd_config

- name: make sure containerd is enabled and started
  systemd:
    name: containerd.service
    enabled: yes
    state: "{% if kubernetes_containerd_config.changed %}re{% endif %}started"
